[book]
language = "es"
multilingual = false
src = "src"
title = "EditoresLand"
author = "EditoresLand contributors"
description = "Conjunto de guías y documentación en español sobre tus editores de texto favoritos"


[output.html]
theme = "./theme"
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["./theme/css/general.css"]
copy-fonts = false
mathjax-support = true
site-url = "/"
git-repository-url = "https://github.com/EditoresLand/book"
edit-url-template = "https://github.com/EditoresLand/book/edit/main/{path}"
input-404 = "not-found.md"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
