name: MdLint 

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    name: Running on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install mdformat
        run: python -m pip install --user mdformat-gfm

      - name: Check mdformat
        run: mdformat --check ./src/ ./README.md

